kind: Namespace
apiVersion: v1

metadata:
  name: nginx
ubuntu@ip-172-31-80-249:~/hpg-k8s$ cat pods.yml 
kind: Pod
apiVersion: v1

metadata:
  name: nginx-pod
  namespace: nginx

spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
